apiVersion: v1
data:
  dbname: "books_db"
  dbuser: "postgres"
  serverport: "7000"
  dbhost: "postgres.postgres-ns.svc.cluster.local:5432"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: books-config-map
  namespace: books-ns
