apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-clain
  namespace: postgres-ns
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi